### ISSUE TITLE
Disable swap

### ISSUE THREAD

**Issue by rgaudin** [offspot/base-image#19]
Choosing whether to use swap or not on our images is important as it defines how we want to handle lack of RAM resources mostly.

Allowing swap means *managing* swap at host and containers level which adds complexity.

We also agree that noswap provides the most reliable and easy-to-recover experience in that containers will be killed.

**Comment by fheslouin** [comment]
I would prefer to disable swap, but our use case is diffrent than yours as we are going to mostly use Raspberry Pi with 8 or 4 GB of RAM. it's unlikely that we will lack of RAM.
