### ISSUE TITLE
IPFS setup

### ISSUE THREAD

**Issue by fheslouin** [offspot/base-image#26]
Currently IPFS setup is done through an [ansible role](https://gitlab.com/bibliosansfrontieres/olip/olip-deploy/blob/e44c474dd313a41d33957bee944e32596be8fe52/roles/ipfs/tasks/main.yml) with it [systemd unit file](https://gitlab.com/bibliosansfrontieres/olip/olip-deploy/blob/1d748d06a75f9ffcd8e632a16da033804b033943/roles/ipfs/templates/ipfs.service.j2)

IPFS needs `fuse` package in order to mounts IPFS to the filesystem.

[IPFS init and custom configuration](https://gitlab.com/bibliosansfrontieres/olip/olip-deploy/blob/upgrade-ipfs-setup/roles/ipfs/tasks/main.yml#L82-111) as well as [enabling systemd unit](https://gitlab.com/bibliosansfrontieres/olip/olip-deploy/blob/upgrade-ipfs-setup/roles/ipfs/handlers/main.yml#L12) will be handled by our `bsf-agent` container.

**Comment by rgaudin** [comment]
Closing as this is not a base-image matter anymore. Follow-up at https://gitlab.com/bibliosansfrontieres/olip/bsf-agent/-/issues/6 ?
