### ISSUE TITLE
TINC setup

### ISSUE THREAD

**Issue by fheslouin** [offspot/base-image#27]
Tinc setup is currently handled by an [ansible role](https://gitlab.com/bibliosansfrontieres/olip-bsf/olip-pre-install/blob/f8e842208568081881603e28090606fbd01c604f/roles/tinc/tasks/main.yml).

Tinc binary can be simply install through package manager, the systemd unit is [available in our repo](https://gitlab.com/bibliosansfrontieres/olip-bsf/olip-pre-install/blob/01e328b51a9019e78cf6c9dde9791a2fa9b7884e/roles/tinc/files/tinc@.service).

`bsf-agent` container will take care of Tinc init process and unit management, however an [interface](https://gitlab.com/bibliosansfrontieres/olip-bsf/olip-pre-install/blob/50795319fbe2eb0044617dcac6ff3dd5dd68d75c/roles/tinc/templates/vpn_interface.j2) has to be created on host

**Comment by fheslouin** [comment]
Unfortunately, yes `testvpn` and a random mac address

**Comment by rgaudin** [comment]
Closing as this is not a base-image matter anymore. Follow-up at https://gitlab.com/bibliosansfrontieres/olip/bsf-agent/-/issues/4 and https://gitlab.com/bibliosansfrontieres/olip/bsf-agent/-/issues/5 ?
