### ISSUE TITLE
PiSugar Power Manager setup

### ISSUE THREAD

**Issue by fheslouin** [offspot/base-image#30]
PiSugar Power Manager is the software that manage the Pi Sugar 3 battery manager.

3 packages needs to be installed in unattended mode : 
* [I2C must be enable](https://gitlab.com/bibliosansfrontieres/olip/olip-deploy/-/blob/master/roles/setup_system/tasks/pisugar-3-plus.yml#L6-18)
* https://gitlab.com/bibliosansfrontieres/olip/olip-deploy/-/blob/master/roles/setup_system/tasks/pisugar-3-plus.yml#L26-28
We will drop a configuration file from the BSF Agent.

The [systemd unit](https://gitlab.com/bibliosansfrontieres/olip/olip-deploy/-/blob/master/roles/setup_system/tasks/pisugar-3-plus.yml#L96-123) for the Raspberry Pi Red LED management is a nice to have, but really BSF and Pi Sugar specific, we might have to drop this feature...to be discuss

**Comment by Popolechien** [comment]
Sure thing. Are speaking about https://www.pisugar.com/ ?

**Comment by kelson42** [comment]
@rgaudin don't forget "our clock module" (for Wikifundi)

**Comment by Bastien-BSF** [comment]
Within BSF we have agreed to give it a try on our side to get this to work as it does not really belong to the base image at the moment.
Closing.
