### ISSUE TITLE
Test moodle over exfat

### ISSUE THREAD

**Issue by rgaudin** [offspot/base-image#4]
Following #3, we need to secure that moodle works fine on exFAT

**Comment by fheslouin** [comment]
Moodle relies on MariaDB and it needs specific ownership and permissions to work, for instance https://gitlab.com/bibliosansfrontieres/olip/apps/mariadb/-/blob/master/entrypoint.sh#L168

Moodle fails as well on startup.sh script : https://gitlab.com/bibliosansfrontieres/olip/apps/moodle/-/blob/master/entrypoint.sh#L22

**Comment by letompouce** [comment]
Moodle and NextCloud both proved we need a permissions/ownership enabled filesystem, which is addressed in #34 .
