### ISSUE TITLE
Add container stack

### ISSUE THREAD

**Issue by rgaudin** [offspot/base-image#6]
We need the base image to have a running container stack with a working docker-compose setup.

We should also have a container-loading mechanism that looks for images tarball in `/data/images` and load them into the container stack on startup, before docker-compose is started.

We also need to generate the docker-compose.yaml file from a script using the list of apps in `/boot/project.json`

- [ ] Container Stack
- [ ] Images-loading script
- [ ] Docker compose setup
- [ ] Docker-compose.yaml generating script from `project.json`
- [ ] Default `project.json` include a very lightweight webserver that solely returns said config file
- [ ] Properly ordered units so docker-compose starts after images are loaded and yaml has been generated 

Images loading pseudo-code

```py
if not images_root.has_files():
   exit()  # continues with docker-compose gen
for file in images_root.all():
    docker.load(file)
    file.unlink()
```

**Comment by rgaudin** [comment]
Logging driver should be configured in order to reduce applications log usage, using the [`local`](https://docs.docker.com/config/containers/logging/local/) driver which is more efficient that default json and is rotated+compressed.

As this goes into the docker.vol I suggest we set conservative default values and allow surcharging those in the compose/description.

@fheslouin @letompouce, what do you think? What about a default of 5MiB per log file with 2 logs on disk with compression enabled ?

That's all per container so with a wild 10 containers installed, that would consume at most 100MiB (less with compression).

**Comment by fheslouin** [comment]
Great, I agree. Defaults values will be enough for our usage however surcharging them can be interesting !
