### ISSUE TITLE
Change WiFi firmware to support more clients

### ISSUE THREAD

**Issue by rgaudin** [offspot/base-image#62]
Stock WiFi firmwares support too few number of clients for use in our Hotspot.
We need to use specific firmware versions with optimized number of clients.
Those are available in IIAB's repo

**Comment by kelson42** [comment]
Seems very important indeed

**Comment by rgaudin** [comment]
Fixed at:

- `base-image` (`1.2.0`)
  - copying all known firmwares to `/lib/firmwares/cypress`
  - backuping original firmware to `xxx_raspios`
  - symlinking firmwares to the best known ones
- `offspot_runtime` (`1.10.0`)
  - new `firmware:` option on [YAML config](https://github.com/offspot/offspot-config/tree/v1.10.0?tab=readme-ov-file#offspotyaml-format)
  - on start, if firmware change is requested, symlinks are updated
  - if firmware changed, reboot is triggered immediately

- This is very similar (but simpler) to what IIAB does.
- We reused IIAB's hand-picked firmwares

**Comment by rgaudin** [comment]
We default to the 30-supporting for Pi3/ZeroW and 24 for the 3B+/4/5. I tested with 7 different devices manually (4 laptops, 3 phones) which is already above the _stock_ (raspios) limit (4/5).
