### ISSUE TITLE
Build image in Github Actions

### ISSUE THREAD

**Issue by rgaudin** [offspot/base-image#8]
Base image must be built inside an Actions workflow:

In addition to building the image, it should be uploaded, zipped:

- onto some stable location for tagged releases
- into another location (tmp.kiwix.org/ci or some S3 bucket) for named branches (manually triggered)

@kelson42 @fheslouin @letompouce we need to clarify destinations

**Comment by kelson42** [comment]
I agree:
* `https://download.offspot.it/base/offspot-base-x.y.z.img` for releases
* S3 for feature branche based temporary images (keep them 30 days)
